name: Python Run and Commit
on:
  push:
    branches:
      - main # 可按需修改为你期望触发此工作流的分支，例如 'dev' 等
jobs:
  python-run-and-commit:
    runs-on: ubuntu-latest # 选择运行环境，这里选 Ubuntu 最新版，也可换其他支持的操作系统环境
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # 检出仓库代码到运行环境中
      - name: Set up Python environment
        uses: actions/setup-python@v4 # 用于设置 Python 环境，默认安装较新版本的 Python
        with:
          python-version: 3.9 # 根据你的 Python 文件实际需求指定版本，如 3.8、3.9 等
      - name: Run Python file
        run: python generate2025.py # 运行你的 Python 文件，这里假设 Python 文件名为 main.py，可按需替换
      - name: Add generated file
        run: git add . # 这里假设生成的文件名为 output.txt，替换成实际生成的文件名，将其添加到暂存区
      - name: Commit changes
        run: |
          git config --global user.name "zrc4889" # 替换为你的 GitHub 用户名
          git config --global user.email "zrc4889@163.com" # 替换为你的 GitHub 注册邮箱
          git commit -m "updated" # 自定义提交信息
      - name: Push changes
        run: git push origin ${{ github.ref }} # 将更改推送到远程仓库对应的分支
